number1 = float(input('==> Enter the first number: \n'))
number2 = float(input('==> Enter the second number: \n'))

print(f'==> {number1} + {number2} = {number1 + number2}')
print(f'==> {number1} - {number2} = {number1 - number2}')
print(f'==> {number1} * {number2} = {number1 * number2}')
print(f'==> {number1} / {number2} = {number1 / number2}')
print(f'==> {number1} // {number2} = {number1 // number2}')
print(f'==> {number1} % {number2} = {number1 % number2}')
print(f'==> {number1} ** {number2} = {number1 ** number2}')